name: Temporary job to test all steps to install kind, vault & crossplane

on:
  workflow_dispatch:
  push:
    branches: [ test_flow ]
    paths-ignore:
      - 'scripts/**' # Ignores bash scripts
      - '*.md'          # Ignores .md files at the root of the repository
      - '**/*.md'       # Ignores .md files within subdirectories

env:
  CONTEXT: "no-tty"

jobs:
  setup-k8s-platform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    env:
      PRIMAZA_GITHUB_REPO: ${{ github.event.pull_request.head.repo.full_name }}
      GITHUB_SHA_COMMIT: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      #- name: Set up JDK 17
      #  uses: actions/setup-java@v3
      #  with:
      #    distribution: 'temurin'
      #    java-version: ${{ matrix.java-version }}
      #    cache: 'maven'
      #- name: Kubernetes KinD Cluster
      #  uses: container-tools/kind-action@v2
      #  with:
      #    version: v0.11.1
      #    registry: true
      - name: Build primaza, generate image, Helm chart and push image
        run: |
          bash ./scripts/primaza.sh
          #bash ./scripts/primaza.sh localdeploy