name: Temporary job to test all steps to install kind, vault & crossplane

on:
  workflow_dispatch:
  push:
    branches: [ test_flow ]
    paths-ignore:
      #- 'scripts/**' # Ignores bash scripts
      - '*.md'          # Ignores .md files at the root of the repository
      - '**/*.md'       # Ignores .md files within subdirectories

env:
  # Variable used disable the pv tool which is not working here as pseudo tty is not supported by action flow
  CONTEXT: "no-tty"

jobs:
  setup-primaza-k8s-platform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    env:
      PRIMAZA_GITHUB_REPO: ${{ github.event.pull_request.head.repo.full_name }}
      PRIMAZA_IMAGE_NAME: $KIND_REGISTRY/local/primaza-app
      PRIMAZA_URL: primaza-app.127.0.0.1.nip.io
      GITHUB_SHA_COMMIT: ${{ github.sha }}

      REGISTRY_NAME: kind-registry
      REGISTRY_PORT: 5000
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Setup Kubernetes using kind and deploy a local container registry
        run: |
          curl -s -L "https://raw.githubusercontent.com/snowdrop/k8s-infra/main/kind/kind.sh" | bash -s install
          
          # Adding registry to /etc/hosts
          echo "127.0.0.1 $REGISTRY_NAME | sudo tee -a /etc/hosts

          # Exporting the registry location for subsequent jobs
          echo "KIND_REGISTRY=${REGISTRY_NAME}:${REGISTRY_PORT}" >> $GITHUB_ENV

      - name: Build primaza, generate image, Helm chart and push image
        run: |
          bash ./scripts/primaza.sh build
      - name: Deploy primaza helm chart
        run: |
          bash ./scripts/primaza.sh localdeploy
      - name: Check pod, services, etc
        run: |
          kubectl get pods -A
          kubectl get svc -A
          kubectl get ingress -A
      - name: Load the data such as cluster, services, credentials & claims
        run: |
          bash ./scripts/primaza.sh loaddata
      - name: Installing vault
        run: |
          bash ./scripts/vault.sh